name: GTesting
favicon: null
layout_spectrum: 0.8508566317614168
typography_spectrum: 0.6392131464090198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4472502926364541
  lightness: 0.5053407347295433
  saturation: 0.21305412240326405
  rhythmicContrast: 0.07953761704266071
purpose: []
